export interface UserInfo {
    EMP_Btype: number;
    EMP_Code: string;
    EMP_CountryID: string;
    EMP_Dept: number;
    EMP_EmailID: string;
    EMP_IsLoyaltyAccepted: boolean | null;
    EMP_IsLoyaltyAccepted_Date: string | null;
    EMP_LoginFlag: "Y" | "N";
    EMP_LoginFlagChangedDate: string | null;
    EMP_Menu: string;
    EMP_Name: string;
    EMP_Password: string;
    EMP_PwdChangeDate: string;
    EMP_ROG_LoginFlag: boolean | null;
    EMP_ROG_LoginFlagChangedDate: string | null;
    EMP_ResetCnt: number;
    EMP_ResetMailSentDate: string | null;
    EMP_RoleId: number;
    EMP_SystemGenPasswordFlag: number;
    EMP_Type: string | null;
    EMP_WrongAttemptCnt: number;
    EMP_WrongMaxCnt: number;
    Is_Multiple_BusinessType: "Yes" | "No";
    Is_Multiple_Login: "Yes" | "No";
    Token: string;
    UPD_BANNED: string;
    UPD_BANNEDON: string;
    UPD_BRANCH: string;
    UPD_COUNTRY: string;
    UPD_MACHINENAME: string;
    UPD_MODULE: string;
    UPD_PROPERTY: string;
    UPD_TODAY: string;
    UPD_USER: string;
}
export type EmpInfo = {
    ASE_PDF_Link: string | null;
    Activation_Update: string;
    BT_Code: string;
    BT_Name: string;
    BT_id: number;
    BannerURL_Link: string;
    Banner_Link: string;
    Branch_Name: string | null;
    DT_Code: string;
    DT_Id: number;
    DT_Name: string;
    DemoHub_Update: string;
    EMP_Code: string;
    EMP_Country: string;
    EMP_EmailID: string;
    EMP_Name: string;
    EMP_Type: string | null;
    ISPSellout_Update: string;
    IsParentCode: boolean;
    Is_LoginAs: string;
    Is_Multiple_Login: string;
    POD_Update: string;
    PerformanceLink: string | null;
    Po_RoleId: number | null;
    RoleCode: string;
    RoleId: number;
    RoleName: string;
    Sellout_Update: string;
    Sellthru_Update: string;
    Sync_Date: string;
    Territory_Name: string | null;
    Year_Qtr: string;
    android_version: string;
    ios_version: string;
    Inventory_Sync_Date: string;
};

